[package]
name = "codenjoy-rust-client"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
pretty_env_logger = "0.5.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tungstenite = { version = "0.20.1", features = ["native-tls"] }
url = "2.4.1"
